CREATE DEFINER = `root` @`localhost` FUNCTION `GET_USERNAME_BY_ID`(UID INT) RETURNS varchar(100) CHARSET utf8mb4 DETERMINISTIC BEGIN DECLARE NAME VARCHAR(100) DEFAULT NULL;
SET 
  NAME = (
    SELECT 
      CONCAT_WS(' ', FIRST_NAME, LAST_NAME) 
    FROM 
      user 
    WHERE 
      ID = UID
  );
RETURN NAME;
end
