CREATE DEFINER = `root` @`localhost` FUNCTION `RELEASE_ALLOCATED_VEHICLES`() RETURNS varchar(100) CHARSET utf8mb4 DETERMINISTIC BEGIN CALL RELEASE_NOT_ACCEPTED_VEHICLES_FROM_TRIP;
CALL RELEASE_WRONG_DCCHECKIN_ALLOCATED_VEHICLES;
RETURN 'Released..!!!';
END
