CREATE DEFINER = `root` @`localhost` PROCEDURE `TERMINATE_TRIP_BY_SOURCE`(IN TRIP_ID INT) BEGIN DECLARE SOURCE VARCHAR(100);
SELECT 
  DISTINCT creation_source 
FROM 
  trip;
SELECT 
  creation_source INTO SOURCE 
FROM 
  trip 
WHERE 
  id = TRIP_ID;
CASE SOURCE WHEN 'OFFLINE_TMS' THEN CALL SOFT_DLT_TRIP_BY_ID(TRIP_ID);
WHEN 'WEB_PORTAL' THEN CALL CANCEL_TRIP_BY_ID(TRIP_ID);
WHEN 'AUTO_ROUTING' THEN CALL DLT_TRIP_BY_ID(TRIP_ID);
WHEN '' THEN 
SELECT 
  'BLANK SOURCE';
ELSE 
SELECT 
  CONCAT_WS(
    '', TRIP_ID, ' TRIP ID NOT FOUND'
  ) 'Result';
END CASE;
END
